In [1]:
# Read all files in pandas

In [1]:
import pandas as pd 
df = pd.read_csv('sales_data_sample.csv', encoding='latin1') # if encoding has wrong then try enconding = 'utf-8'
df
# , encoding='utf-8'
# , encoding='latin1' 
# first we read csv file in jupyter notebook

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [7]:
import pandas as pd 
df = pd.read_json('sample_Data.json')
df
# first we read csv file in jupyter notebook

,id,name,description,price,category,image
0,1,Apple iPhone 12,The Apple iPhone 12 features a 6.1-inch Super ...,999.00,Electronics,https://www.apple.com/newsroom/images/product/...
1,2,Samsung Galaxy S21,The Samsung Galaxy S21 features a 6.2-inch Dyn...,799.00,Electronics,https://images.samsung.com/is/image/samsung/p6...
2,3,Sony PlayStation 5,The Sony PlayStation 5 features an AMD Zen 2-b...,499.99,Electronics,https://www.sony.com/image/44baa604124b770c824...
3,4,LG OLED55CXPUA 55-inch 4K OLED TV,The LG OLED55CXPUA 55-inch 4K OLED TV features...,1599.99,Electronics,https://www.lg.com/us/images/tvs/md07501804/ga...
4,5,Bose QuietComfort 35 II Wireless Headphones,The Bose QuietComfort 35 II Wireless Headphone...,299.00,Electronics,https://assets.bose.com/content/dam/Bose_DAM/W...
5,6,Fitbit Versa 3 Smartwatch,The Fitbit Versa 3 Smartwatch features a built...,229.95,Electronics,https://www.fitbit.com/global/content/dam/fitb...
6,7,KitchenAid Stand Mixer,The KitchenAid Stand Mixer features a 5-quart ...,399.99,Home & Kitchen,https://www.kitchenaid.com/content/dam/global/...
7,8,Dyson V11 Absolute Cordless Vacuum,The Dyson V11 Absolute Cordless Vacuum feature...,699.99,Home Appliances,https://www.dysoncanada.ca/dam/dyson/images/pr...
8,9,Ninja Foodi Smart XL Grill,The Ninja Foodi Smart XL Grill features 6-in-1...,279.99,Home & Kitchen,https://www.ninjakitchen.com/medias/Ninja-OP50...
9,10,Canon EOS Rebel T8i DSLR Camera,The Canon EOS Rebel T8i DSLR Camera features a...,899.00,Electronics,https://www.canon.com.au/-/media/images/produc...
10,11,Apple AirPods Pro,The Apple AirPods Pro feature active noise can...,249.00,Electronics,https://www.apple.com/v/airpods-pro/b/images/m...
11,12,Bose QuietComfort 35 II Wireless Headphones,The Bose QuietComfort 35 II Wireless Headphone...,299.00,Electronics,https://assets.bose.com/content/dam/Bose_DAM/W...
12,13,Fitbit Charge 4 Fitness Tracker,The Fitbit Charge 4 Fitness Tracker features G...,129.95,Electronics,https://www.fitbit.com/global/content/dam/fitb...
13,14,Samsung Galaxy Watch3,The Samsung Galaxy Watch3 features a rotating ...,399.99,Electronics,https://images.samsung.com/is/image/samsung/as...
14,15,Sony WH-1000XM4 Wireless Noise-Cancelling Head...,The Sony WH-1000XM4 Wireless Noise-Cancelling ...,349.99,Electronics,https://www.sony.com/image/1cdd6354c4cd21cc4f7...
15,16,Breville Barista Express Espresso Machine,The Breville Barista Express Espresso Machine ...,699.95,Home & Kitchen,https://www.breville.com/content/dam/breville/...
16,17,Keurig K-Elite Coffee Maker,The Keurig K-Elite Coffee Maker features a str...,169.99,Home & Kitchen,https://www.keurig.com/content/dam/global-ecom...
17,18,iRobot Roomba i7+ Robot Vacuum,The iRobot Roomba i7+ Robot Vacuum features au...,799.99,Home & Kitchen,https://store.irobot.com/default/i7-vacuuming-...
18,19,Ninja Foodi Digital Air Fry Oven,The Ninja Foodi Digital Air Fry Oven features ...,209.99,Home & Kitchen,https://www.ninjakitchen.com/static/img/produc...
19,20,Cuisinart ICE-70 Ice Cream Maker,The Cuisinart ICE-70 Ice Cream Maker features ...,139.99,Home & Kitchen,https://www.cuisinart.com/share/images/product...

In [19]:
import pandas as pd

# Use pd.read_excel() for reading .xls files
df = pd.read_excel('SampleSuperstore.xls')  # xlrd is used for older .xls formats

# Display the DataFrame
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [12]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\shahbaz junaid\downloads\compressed\python\lib\site-packages (2.2.1)
Requirement already satisfied: openpyxl in c:\users\shahbaz junaid\downloads\compressed\python\lib\site-packages (3.1.2)
Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\shahbaz junaid\downloads\compressed\python\lib\site-packages (from pandas) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shahbaz junaid\downloads\compressed\python\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\shahbaz junaid\downloads\compressed\python\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shahbaz junaid\downloads\compressed\python\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: et-xmlfile in c:\users\shahbaz junaid\downloads\compressed\python\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\shahbaz junaid\downloads\compressed\python\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)